# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow installs Deno, runs lint, and generates SLSA provenance
name: Deno

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write  # needed for SLSA
  attestations: write  # needed for SLSA

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@f3d8fb78b1c082eefbb8daaf6e2b6c7e1c4e7f6a # v2.0.2
        with:
          deno-version: v1.x

      - name: Lint
        run: deno lint

      - name: Format check
        run: deno fmt --check
